---
title: "Rproject_template"
author: "Author"
date: "`r format(Sys.time(), '%Y/%m/%d')`"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
    toc_depth: 2
    theme: spacelab
    highlight: haddock
    fig_caption: yes
    fig_width: 9
    fig_height: 8
    self_contained: true
    #css: mystyle.css
    md_extensions: -ascii_identifiers
---

# セットアップ

## ライブラリーの読み込み

```{r setup-load-library, results='hide'}
library(tidyverse) # recommend # see https://heavywatal.github.io/rstats/programming.html
library(here) # recommend # see https://uribo.hatenablog.com/entry/2018/01/25/082000
library(patchwork) # recommend # see https://qiita.com/nozma/items/4512623bea296ccb74ba
```


## 関数の読み込み

```{r setup-load-functions, results='hide'}
# プロジェクトで共通で使う関数は、_functionsフォルダに作成して、source()で読み込むこと
functions_path <- here("Analysis_Script", "_functions")
target_functions <- here(functions_path, dir(functions_path))

purrr::walk(target_functions, ~source(.x))
# source()は複数の関数を読み込めないので、purrr::walk()を使う
# purrr::walk()は、vector (or list) を関数に適用しながらinvisible返しする、purrr::mapの亜種
```


## メタ情報の設定

```{r setup-knit-environment, results='hide'}
# knit時の各種設定
# 特に、cacheを _cacheフォルダに生成するための設定

rmarkdown_dir <- "Analysis_Script"
cache_dir <- "_cache" # cacheの保存ディレクトリ名
input <- knitr::current_input() %>% str_split(pattern = "\\.Rmd") # 拡張子の前だけ取り出す

knitr::opts_chunk$set(
  echo=TRUE, comment="", warning=FALSE, message=FALSE, fig.align="center",
  
  cache.path = here(rmarkdown_dir, cache_dir, input[[1]][1] %&% "_cache", "html") %&% "/", 
  fig.path = here(rmarkdown_dir, cache_dir, input[[1]][1] %&% "_files", "figure-html") %&% "/"
  )
```

```{r setup-output-path}
# 出力の保存先のパスを設定
# dir.create(here("Output", "Figures")) # なければ、フォルダを作成
output_path <- here("Output", "Figures")
```


## データの読み込み

```{r}
# --- load data --- #
# デフォルトで、Data/DummyData_RL/に3つのダミーデータのディレクトリがあるはず
# テストとして、それらを読み込んでデータフレームにする
## ディレクトリがなければ、generate_DummyData_RL.R or generate_DummyData_RL.py のどちらかを実行してcsvを生成しておく
# --- --- #

options(readr.num_columns = 0) # readrのメッセージがうるさいので消す

DataDir <- "Data"
DataDir_sub <- "DummyData_RL"

target_csv <- make_CSVPath(DataDir, DataDir_sub, ".", ".csv")
df_dummy_RL <- purrr::map_dfr(target_csv, readr::read_csv)
# 複数のcsv（列構造が同じもの）は、purrr::map_dfr()がrapid & beautifulで良い
# csvが巨大な場合には、purrr::map_dfr(target_csv, data.table::fread)を実行すると良い
```


# 概要

これまでの分析の要約、今回の分析の目的、どんな分析をやったのかの要約を列挙する


# 分析1：試行を通してのQ値と選択の変化

```{r}
# --- 作図の基本的な方針 --- #
## 横軸や縦軸などのパラメータが同じで、与えるデータフレームだけが異なる場合は、
## 作図を関数化して、purrr::mapで作成する
## or %+% でデータだけ置き換えることで作成する
## なるべく ggsave()でpng保存する ← 論文や学会スライドの際にすぐ利用できるように
## Figureの保存先は、Output/Figures/
# --- --- --- #




```


## 報酬確率0.6 vs 0.4

## 



## 



# 分析2：



# SessionInfo

```{r}
sessionInfo()
```


